spring:
  profiles:
    include:
      - secret

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:db

  jpa:

    open-in-view: off

    properties:
      hibernate:
        hbm2ddl:
          auto: update