name: ci-cd

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

jobs:
  buid:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPO }}

      #      - name: Copy compose file to server
      #        uses: appleboy/scp-action@master
      #        with:
      #          host: ${{ secrets.SERVER_IP }}
      #          username: ${{ secrets.SERVER_USER }}
      #          key: ${{ secrets.SERVER_SSH_KEY }}
      #          source: "./docker-compose.yml"
      #          target: "/home/ubuntu/docker1"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker stop woozy9/consumer:latest
            docker rm woozy9/consumer:latest
            docker run -d -p 8080:8080 woozy9/consumer:latest